version: "3.2"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
  # APP*****************************************
  springbootapp:
    restart: always
    build: .
    container_name: springbootapp
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis